apex: true
batch_size: 16
ccp_pooling_last: 4
clip_grad_norm: true
criterion: ce
cv_strat: multilabel_stratified_kfold
data_path: /content/drive/MyDrive/lal-aes2/data/learning-agency-lab-automated-essay-scoring-2/
decoder_lr: 1.0e-05
encoder_lr: 1.0e-05
exp: D012
extra_data_path: /content/drive/MyDrive/lal-aes2/data/persuade_data/
freeze_embeddings: false
freeze_n_layers: 0
gradient_checkpointing: true
lstm_hidden: 1024
max_grad_norm: 1.0
max_len: 1024
model_name: microsoft/deberta-v3-small
multi_dropout: true
num_epochs: 3
num_folds: 4
num_labels: 7
optim_betas1: 0.9
optim_betas2: 0.999
optim_eps: 1.0e-06
optimizer: adamw
poly_power: 0.05
pooling_layer: mean_pooling
save_path: /content/drive/MyDrive/lal-aes2/expD012/
scheduler: linear_warmup
seed: 42
target_col: discourse_type
train_col: discourse_text
train_fold_list:
- 0
- 1
- 2
- 3
verbose_step: 400
warmup_ratios: 0.1
weight_decay: 0.01
wlp_layer_start: 4
